# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  s3_bucket: "crankstart-dev"
production:
  s3_bucket: 'crankstart-pro'

s3_region: "us-east-1"
s3_access_key_id: "AKIAIPHQ2P2M6YXCGDGQ"
s3_secret_access_key: "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"
